version: '3.7'

networks:
  default:

services:
###> alexanderweigelt/devbox-db ###
  db:
    image: alexanderweigelt/devbox-db:${IMAGE_TAG}
    networks:
      default: { }
    ports:
      - ${PORT_MYSQL}:3306
    volumes:
      - dbdata:/var/lib/mysql:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/mysql:rw
    env_file:
      - .env
###< alexanderweigelt/devbox-db ###

###< alexanderweigelt/devbox-httpd ###
  httpd:
    image: alexanderweigelt/devbox-httpd:${IMAGE_TAG}
    networks:
      default: { }
    ports:
      - ${PORT_HTTP}:80
    volumes:
      - ${COMPOSE_PROJECT_ROOT}:${HTTP_PROJECT_ROOT}:rw
    env_file:
      - .env
###< alexanderweigelt/devbox-httpd ###

###> alexanderweigelt/devbox-php ###
  php:
    image: alexanderweigelt/devbox-php:${IMAGE_TAG}
    networks:
      default: { }
    volumes:
      - ${COMPOSE_PROJECT_ROOT}:${HTTP_PROJECT_ROOT}:rw
    env_file:
      - .env
###< alexanderweigelt/devbox-php ###

###> alexanderweigelt/devbox-toolbox ###
  toolbox:
    image: alexanderweigelt/devbox-toolbox:${IMAGE_TAG}
    networks:
      default: { }
    ports:
      - ${PORT_SSH}:22
    volumes:
      - ${COMPOSE_PROJECT_ROOT}:${HTTP_PROJECT_ROOT}:rw
    depends_on:
      - php
      - db
    env_file:
      - .env
###< alexanderweigelt/devbox-toolbox ###

volumes:
  dbdata:
    driver: local
